#!/usr/bin/bash

docklog() {
  id=$(docker ps --all=true | grep "$1" | head -n1 | awk '{print $1}')
  echo "----- docker log for $id -----"
  docker logs "$id"
  echo
}

docknuke() {
  echo "Nuking all docker containers!"
  for i in `docker ps --all=true | grep -v CONTAINER | awk '{print $1}'`
    do
      docker rm -f "$i";
    done
  echo
}

dockssh() {
  id=$(docker ps --all=true | grep "$1" | head -n1 | awk '{print $1}')
  echo "----- connecting to docker $id -----"
  docker exec -ti "$id" sh
  echo
}

docksee() {
  id=$(docker ps --all=true | grep "$1" | head -n1 | awk '{print $1}')
  echo "----- docker inspect for $id -----"
  docker inspect "$id"
  echo
}

find_big_docker_logs() {
  dockerpath='/var/lib/docker/containers/'
  size="$1"
  #size='1G'
  find=$(which find)

  logs=$("$find" "$dockerpath" -type f -name "*-json.log" -size +"$size")
  # find /var/lib/docker/containers/ -type f -name "*-json.log" -size +5G

  echo "$logs"
}
